[project]
name = "oisol_db_support"
dynamic = ["version"]
requires-python = ">= 3.13"
dependencies = [
    "pandas",
    "polars",
    "pyarrow",
    "sqlalchemy",
]

[tool.pytest.ini_options]
pythonpath = [
  ".",
]
