target-version = "py313"
exclude = [
    "__init__.py",  # Waiting for non preview fixes for F401 & F403
    "tests/"
]

[lint]
select = [
    "E", "W", # Pycodestyle
    "F", # Pyflakes
    "UP", # Pyupgrade
    "B", # Flake8-bugbear
    "SIM", # Flake8-simplify
    "I", # Isort
    "C4", # Comprehensions
    "T20", # Prints
    "ANN", # Types annotation
    "COM", # Commas handling
    "Q", # Quoting
    "RET", # Return
    "ERA", # Commented code
    "TRY", # Tryceratops (Exception related)
    "RUF", # Ruff specific rules
    "N", # Pep-8 naming conventions
    "PERF", # Performances
]
ignore = [
    "E501", # Line-too-long
    "ANN204", # Missing-return-type-special-method
    "ANN002", # Args typing
    "ANN003", # Kwargs typing
    "RUF001", # Unicode chars
    "TRY400", # Exception instead of error
    "RUF012", # Mutable-class-default
    "W191", # Indentation contains tabs
]

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"

[format]
indent-style="space"
quote-style="single"